# This is a basic workflow to help you get started with Actions

name: Sync labels for repository set

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-labels:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Repository set labels sync
        uses: gimli01/repository-set-labels-sync@v1.3.2
        with:
          data-directory: "data/"
          repositories-filename: "repositories.json"
          labels-filename: "labels.json"
          token: ${{ secrets.SYNC_LABELS_PAT }}
